### ISSUE TITLE
Trouble "logging in" into the dashboard 

### ISSUE THREAD

**Issue by anishaswain** [distributed-system-analysis/pbench-dashboard#165]
Having `bad login` error on dashboard while trying to login. 
<img width="1096" alt="Screenshot 2021-06-01 at 6 33 44 PM" src="https://user-images.githubusercontent.com/16955978/120327918-eb9c2b80-c307-11eb-94ef-7bd5b313763f.png">
![imageedit_2_3739648978](https://user-images.githubusercontent.com/16955978/120328692-b5ab7700-c308-11eb-9114-58a333938d5f.png)

**Comment by anishaswain** [comment]
@dbutenhof @npalaska @portante I am using the same updates `endpoint.js` file as sent by Dave in the gchat.

**Comment by dbutenhof** [comment]
Did you try to use the dashboard Register User page? I don't see an `aswain@redhat.com` user in the database. And I see failed login attempts, but no failed registration attempts.

**Comment by anishaswain** [comment]
> Did you try to use the dashboard Register User page? I don't see an `aswain@redhat.com` user in the database. And I see failed login attempts, but no failed registration attempts.

I did try to register. It didn't give error. It simply redirected me.

**Comment by dbutenhof** [comment]
Interesting; you should try that with the Chrome console up to see what network requests it's making, and what it gets back.

The server logs don't show any /api/v1/register calls since May 20.

**Comment by dbutenhof** [comment]
For what it's worth, I just verified that I can register a new user with the dashboard that's deployed to 10.1.170.246 now, and that the success shows up in the NGINX access_log.

(Although I had to update the deployed dashboard since it was still running a version prior to my May 13 to the `/api/v1/register` JSON parameter names; that shouldn't have affected you if you're running your own local `yarn start` rather than using the deployed code. And the error would have shown up in the logs in any case.)

**Comment by anishaswain** [comment]
Already fixed I believe. @portante, @dbutenhof can we close it? Any related PR to link here?

**Comment by dbutenhof** [comment]
If we did anything to "fix" this, I didn't record it. It may have been the version skew I mentioned in the comment on June 1, if you were somehow running dashboard code prior to a dashboard fix that had already been merged by this point.

I say just close it at this point, but I'll leave that to you since I don't have anything definitive.

**Comment by dbutenhof** [comment]
Closing this; our thinking was that it was probably due to a version skew during testing, and wasn't fixed by any specific PR.
