### ISSUE TITLE
The summary page for a controller  throws multiple errors

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#48]
What I inferred from running summaries from a particular controller is that the page throws quite different errors, 2 of them being most significant as in now.

## Error 1:
<img width="1436" alt="Screenshot 2020-05-11 at 12 20 47 PM" src="https://user-images.githubusercontent.com/26324376/81532517-25f3fd00-9382-11ea-866a-a34e5aa3e70e.png">

>This is a relatively easier issue to handle cause there are "unique key" and an "invalid prop" errors.

## Error 2:
<img width="1438" alt="Screenshot 2020-05-11 at 12 25 15 PM" src="https://user-images.githubusercontent.com/26324376/81532727-7f5c2c00-9382-11ea-8234-35a72aa7feaa.png">

> I have little idea about why this happens. There is no stack trace of the error.

**Comment by aquibbaig** [comment]
@gurbirkalsi @Anisha1234 Anybody got any fix for this?

**Comment by anishaswain** [comment]
**Case-1**
Can be resolved by removing {} from Option in line no 7 of `TableFilterSelection`
(Some other warnings are thrown becasue in Ant Design every row of a table should have a unique `rowKey` (rowKey, could be a string or function that returns a string)

**Case-2**
@aquibbaig. I guess the second error is thrown because the hits returned from Elasticsearch is empty
![Screenshot from 2020-05-11 14-27-26](https://user-images.githubusercontent.com/16955978/81543879-55ac0080-9394-11ea-90bc-21c9247e290a.png)

@gurbirkalsi I discussed with Peter regarding this and found out that we are getting into trouble in case 2 because the `run.id` that we are querying doesn't exists in elasticsearch. 

In typical case, we should go back to the previous page (which I believe @gurbirkalsi has already implemented before). @gurbirkalsi as much as I know we used to check the response before rendering the next page right?

**Comment by aquibbaig** [comment]
@Anisha1234 The current screenshot which I had for "Case 2", I sent a curl to that URL and I found 9 hits to be exact but still the error persists.

**Comment by anishaswain** [comment]
> @Anisha1234 The current screenshot which I had for "Case 2", I sent a curl to that URL and I found 9 hits to be exact but still the error persists.

@aquibbaig 
![Screenshot from 2020-05-11 15-24-46](https://user-images.githubusercontent.com/16955978/81548873-8fccd080-939b-11ea-9148-096c79226960.png)
The response from the URL(endpoint) is again getting aggregated and filtered again which is reducing the number of hits. However, by only hitting the endpoint it is returning around `15400175` hits .

**Comment by aquibbaig** [comment]
@Anisha1234 So, in the end there are no hits?

**Comment by anishaswain** [comment]
> @Anisha1234 So, in the end there are no hits?

Yes, in that specific case, no hits are returned.

**Comment by anishaswain** [comment]
Error-2 deals with issue #16

**Comment by portante** [comment]
We need to be able to handle the case where a query returns nothing.  For this particular case, we had an error indexing the data which resulted in no result data documents being indexed.

**Comment by gurbirkalsi** [comment]
@aquibbaig Thanks for reporting this issue, both of these errors are being addressed with PR #41

**Comment by anishaswain** [comment]
@gurbirkalsi wrt #41 should we close this issue?

**Comment by portante** [comment]
Fixed by #41.
